const orders = [
    {
        id: 0,
        item: 'IPhone',
        amount: 2,
        price: 500.4,
        seller: 'Apple',
        status: 'Pending',
        created_at: '01/03/2014',
        image: require("../assets/Iphone.jpg"),
    },
    {
        id: 1,
        item: 'Macbook',
        amount: 3,
        price: 999.40,
        seller: 'Apple',
        status: 'Delivered',
        created_at: '21/03/2014',
        image: require("../assets/Macbook.jpg"),
    },
    {
        id: 2,
        item: 'Bing Headphones',
        amount: 1,
        price: 20,
        seller: 'Bing',
        status: 'Delivered',
        created_at: '10/03/2014',
        image: require("../assets/Headphone.jpg"),
    },
    {
        id: 3,
        item: 'IPhone',
        amount: 1,
        price: 250.2,
        seller: 'Apple',
        status: 'Cancelled',
        created_at: '20/03/2014',
        image: require("../assets/Iphone.jpg"),
    },
    {
        id: 4,
        item: 'Mackbook',
        amount: 4,
        price: 1800.80,
        seller: 'Apple',
        status: 'Pending',
        created_at: '29/03/2014',
        image: require("../assets/Macbook.jpg"),
    },
    {
        id: 5,
        item: 'Macbook',
        amount: 3,
        price: 999.40,
        seller: 'Apple',
        status: 'Delivered',
        created_at: '21/03/2014',
        image: require("../assets/Macbook.jpg"),
    },
    {
        id: 5,
        item: 'Bing Headphones',
        amount: 1,
        price: 20,
        seller: 'Bing',
        status: 'Canceled',
        created_at: '10/03/2014',
        image: require("../assets/Headphone.jpg"),
    },
];

export default orders;
