const products = {
    sale: [
        {
            id: 0,
            title: "Macbook",
            images: [require("../assets/Macbook.jpg"),require("../assets/Macbook2.jpg"),require("../assets/Macbook3.jpg"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 100,
            rating: '4.0',
            discount: 20,
            tag: "Free shipping",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 1,
            title: "Bing Headphone",
            images: [require("../assets/Headphone.jpg"),require("../assets/Headphone2.jpg"),
        ],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 130,
            rating: '3.0',
            discount: 20,
            tag: "Free shipping",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 2,
            title: "Iphone",
            images: [require("../assets/Iphone.jpg"),require("../assets/Iphone2.jpg"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 50,
            rating: '3.5',
            discount: 20,
            tag: "Free shipping",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 3,
            title: "Macbook",
            images: [require("../assets/Macbook.jpg"),require("../assets/Macbook2.jpg"),require("../assets/Macbook3.jpg"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 100,
            rating: '3.0',
            discount: 20,
            tag: "Free shipping",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 4,
            title: "Bing Headphone",
            images: [require("../assets/Headphone.jpg"),require("../assets/Headphone2.jpg"),
        ],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 130,
            rating: '3.0',
            discount: 20,
            tag: "Free shipping",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 5,
            title: "Iphone",
            images: [require("../assets/Iphone.jpg"),require("../assets/Iphone2.jpg"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 50,
            rating: '3.0',
            discount: 20,
            tag: "Free shipping",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
    ],
    new: [
        {
            id: 0,
            title: "Aliquip",
            images: [require("../assets/Product.png"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 100,
            rating: '3.0',
            discount: 0,
            tag: "New",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 1,
            title: "Exercitation",
            images: [require("../assets/Product2.png"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 130,
            rating: '3.0',
            discount: 0,
            tag: "New",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 2,
            title: "Eiusmod",
            images: [require("../assets/Product3.png"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 50,
            rating: '3.0',
            discount: 0,
            tag: "New",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 3,
            title: "Veniam",
            images: [require("../assets/Product.png"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 190,
            rating: '3.0',
            discount: 0,
            tag: "New",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 4,
            title: "Est minim",
            images: [require("../assets/Product2.png"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 200,
            rating: '3.0',
            discount: 0,
            tag: "New",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 5,
            title: "Ea ullamco",
            images: [require("../assets/Product3.png"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 105,
            rating: '3.0',
            discount: 0,
            tag: "New",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
        {
            id: 6,
            title: "Commodo",
            images: [require("../assets/Product.png"),],
            description:
                "Esse adipisicing tempor occaecat magna nulla culpa consectetur. Incididunt ad incididunt nisi Lorem enim deserunt Lorem nostrud quis excepteur laborum cupidatat qui Lorem. Occaecat enim consectetur eiusmod nostrud sint velit Lorem Lorem aute. Nostrud tempor Lorem dolor fugiat laborum amet mollit consectetur id nisi. Laboris consequat qui sint non ipsum qui quis. Et incididunt magna voluptate sit exercitation consequat ea amet labore do deserunt id. In minim fugiat esse minim ea velit sint veniam voluptate reprehenderit occaecat.",
            price: 40,
            rating: '3.0',
            discount: 0,
            tag: "New",
            variants: ["#3F4343", "#CCC6BA", "#CFCFCF"],
        },
    ],
};

export default products;
